export type FirebaseUser = { uid: string; displayName: string | null; email: string | null };
export type StoredMember = { id: string; username: string; displayName: string; email: string; birthday: string; role: 'admin' | 'member'; uid?: string; bio?: string; aiBio?: string; avatar?: string };
type Doc = { get(): Promise<{ exists: boolean; data(): unknown }>; set(data: unknown, options?: { merge: boolean }): Promise<void> };
type Store = { collection(name: string): { doc(id: string): Doc } };
type FirebaseCompat = { apps: unknown[]; initializeApp(config: Record<string, string>): unknown; auth: (() => { signInWithPopup(provider: unknown): Promise<{ user: FirebaseUser }> }) & { GoogleAuthProvider: new () => unknown }; firestore(): Store };
declare global { interface Window { firebase?: FirebaseCompat } }
const config = { apiKey: import.meta.env.VITE_FIREBASE_API_KEY, authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN, projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID, storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET, messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID, appId: import.meta.env.VITE_FIREBASE_APP_ID };
function loadScript(src: string) { return new Promise<void>((resolve, reject) => { const found = document.querySelector<HTMLScriptElement>(`script[src="${src}"]`); if (found) { if (window.firebase) resolve(); else { found.addEventListener('load', () => resolve(), { once: true }); found.addEventListener('error', () => reject(new Error('No se pudo cargar Firebase.')), { once: true }); } return; } const script = document.createElement('script'); script.src = src; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error('No se pudo cargar Firebase.')); document.head.appendChild(script); }); }
export async function firebaseStore() { if (!Object.values(config).every(Boolean)) throw new Error('Firebase no está configurado.'); await loadScript('https://www.gstatic.com/firebasejs/10.12.5/firebase-app-compat.js'); await loadScript('https://www.gstatic.com/firebasejs/10.12.5/firebase-auth-compat.js'); await loadScript('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore-compat.js'); const firebase = window.firebase; if (!firebase) throw new Error('Firebase no se pudo inicializar.'); if (!firebase.apps.length) firebase.initializeApp(config as Record<string, string>); return firebase.firestore(); }
export async function signInWithFirebaseGoogle(): Promise<FirebaseUser> { await firebaseStore(); const firebase = window.firebase!; return (await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider())).user; }
export async function seedMembers(members: StoredMember[]) { const db = await firebaseStore(); await Promise.all(members.map(async (member) => { const ref = db.collection('members').doc(member.id); const saved = await ref.get(); if (!saved.exists) await ref.set(member); })); }
export async function readMember(id: string) { const doc = await (await firebaseStore()).collection('members').doc(id).get(); return doc.exists ? doc.data() as StoredMember : null; }
export async function findMemberByUid(uid: string, ids: string[]) { for (const id of ids) { const member = await readMember(id); if (member?.uid === uid) return member; } return null; }
export async function claimMember(id: string, user: FirebaseUser) { const db = await firebaseStore(); const ref = db.collection('members').doc(id); const current = await ref.get(); if (!current.exists) throw new Error('El integrante no existe.'); const member = current.data() as StoredMember; if (member.uid && member.uid !== user.uid) throw new Error('Ese integrante ya vinculó su cuenta de Google.'); await ref.set({ uid: user.uid, googleEmail: user.email, googleName: user.displayName, linkedAt: Date.now() }, { merge: true }); return { ...member, uid: user.uid }; }
export async function saveMember(id: string, values: Partial<StoredMember>) { await (await firebaseStore()).collection('members').doc(id).set(values, { merge: true }); }
